# Generated by Django 2.0.2 on 2019-07-19 13:30

from django.conf import settings
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('group_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('group_name', models.CharField(max_length=50)),
                ('group_limit', models.IntegerField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('amount_to_save', models.IntegerField()),
                ('is_public', models.BooleanField()),
                ('g_users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
