# Generated by Django 2.0.2 on 2019-07-19 17:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('esusuaapi', '0004_auto_20190719_1615'),
    ]

    operations = [
        migrations.CreateModel(
            name='Userprofile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_no', models.CharField(blank=True, max_length=11)),
                ('phone_no', models.CharField(blank=True, max_length=11)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('groups', models.ManyToManyField(to='esusuaapi.EsusuGroup')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='contribution',
            name='esusu_name',
        ),
        migrations.DeleteModel(
            name='Contribution',
        ),
    ]
