# Generated by Django 2.0.2 on 2019-07-20 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esusuaapi', '0005_auto_20190719_1851'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_no', models.CharField(max_length=12)),
            ],
        ),
        migrations.RemoveField(
            model_name='esusugroup',
            name='g_users',
        ),
        migrations.RemoveField(
            model_name='esusugroup',
            name='group',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='EsusuGroup',
        ),
        migrations.DeleteModel(
            name='Userprofile',
        ),
    ]
