# Generated by Django 2.0.2 on 2019-07-20 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('esusuaapi', '0006_auto_20190720_1259'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
