# Generated by Django 2.0.2 on 2019-07-20 15:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('esusuaapi', '0009_esusugroup_group_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='esusugroup',
            options={'verbose_name_plural': 'EsusuGroups'},
        ),
        migrations.AlterField(
            model_name='esusugroup',
            name='amount_to_save',
            field=models.PositiveIntegerField(),
        ),
        migrations.RemoveField(
            model_name='esusugroup',
            name='g_users',
        ),
        migrations.AddField(
            model_name='esusugroup',
            name='g_users',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='esusugroup',
            name='group_limit',
            field=models.PositiveIntegerField(),
        ),
    ]
