# Generated by Django 2.0.2 on 2019-07-20 15:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('esusuaapi', '0011_auto_20190720_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='esusugroup',
            name='g_users',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
