# Generated by Django 2.0.2 on 2019-07-20 15:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('esusuaapi', '0012_auto_20190720_1638'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='esusugroup',
            name='g_users',
        ),
        migrations.AddField(
            model_name='esusugroup',
            name='g_users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
