# Generated by Django 2.0.2 on 2019-07-20 15:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('esusuaapi', '0014_remove_esusugroup_g_users'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='esusugroup',
            options={},
        ),
        migrations.AddField(
            model_name='esusugroup',
            name='g_users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='esusugroup',
            name='amount_to_save',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='esusugroup',
            name='group_limit',
            field=models.IntegerField(),
        ),
    ]
