# Generated by Django 2.0.2 on 2019-07-20 15:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('esusuaapi', '0015_auto_20190720_1644'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='esusugroup',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.RemoveField(
            model_name='esusugroup',
            name='g_users',
        ),
        migrations.AddField(
            model_name='esusugroup',
            name='g_users',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
