# Generated by Django 2.0.2 on 2019-07-20 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('esusuaapi', '0016_auto_20190720_1652'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='esusugroup',
            options={'verbose_name_plural': 'Esusu Groups'},
        ),
    ]
